##########
# SERVER #
##########

HOSTNAME: localhost
APP_DEBUG: false
# httpx debug mode is very verbose, so the setting is separate from the main app debug mode
HTTPX_DEBUG: false
DOCS_URL_PREFIX: /gen3workflow

# override the default Arborist URL; ignored if already set as an environment variable
ARBORIST_URL:

# /!\ only use for development! Allows running gen3workflow locally without Arborist interaction
MOCK_AUTH: false

##########
# AWS S3 #
##########

USER_BUCKETS_REGION: us-east-1

# objects created in S3 for/by workflows are deleted after the specified number of days
S3_OBJECTS_EXPIRATION_DAYS: 30

# configure an AWS IAM key to use when making S3 requests on behalf of users. If left empty, it
# is assumed there is an existing STS session we can get credentials from.
S3_ENDPOINTS_AWS_ACCESS_KEY_ID:
S3_ENDPOINTS_AWS_SECRET_ACCESS_KEY:

KMS_ENCRYPTION_ENABLED: true


#############
# GA4GH TES #
#############

TES_SERVER_URL: http://funnel:8000

# List of whitelisted images to be allowed by the Gen3Workflow Service to forward to TES server.
# Image names can contain wildcards with `*` and username as a placeholder within curly braces e.g. {username}
TASK_IMAGE_WHITELIST: []
  # - public.ecr.aws/random/approved/public:*
  # - 9876543210.dkr.ecr.us-east-1.amazonaws.com/approved/{username}:abc
  # - quay.io/nextflow/bash:*

#############
#  METRICS  #
#############

ENABLE_PROMETHEUS_METRICS: false
PROMETHEUS_MULTIPROC_DIR: /var/tmp/prometheus_metrics

#################
#  EKS CLUSTER  #
#################

# When Gen3Workflow runs on an EKS cluster, it relies on IAM Roles for Service Accounts (IRSA)
# to provide AWS permissions to Funnelâ€™s worker and executor pods.
#
# The parameters below are required for Gen3Workflow to:
#   - Identify the Kubernetes namespace where worker pods run, to construct the correct IAM role trust relationship
#   - Fetch cluster's OIDC provider URL based on the given cluster name and region
#
# In short: these values allow Gen3Workflow to generate per-user IAM roles that EKS will recognize and associate
# with the corresponding service accounts used by Funnel pods.

WORKER_PODS_NAMESPACE: default-namespace
EKS_CLUSTER_NAME: ""
EKS_CLUSTER_REGION: us-east-1
